parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    Application\:
        resource: "../src/Application/"

    Infrastructure\:
        resource: '../src/Infrastructure/'
        exclude:
            - '../src/Infrastructure/Symfony/DependencyInjection/'
            - '../src/Infrastructure/Symfony/Kernel.php'
