version: "3.8"

services:
  reverse-proxy:
    image: traefik:v2.4.7
    container_name: traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./docker/traefik/dynamic_conf.yaml:/etc/traefik/dynamic_conf.yaml:ro
      - ./docker/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./certs:/etc/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  frontend:
    build: ./docker/node
    restart: unless-stopped
    env_file: ./apps/frontend/.env
    volumes:
      - ./apps/frontend:/app:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.app.localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  nginx:
    image: nginx:1.20.2-alpine
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.rule=Host(`backend.app.localhost`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./apps/backend:/app:ro
    depends_on:
      - php
  
  php:
    build:
      context: ./docker/php
      target: dev
    env_file: ./apps/backend/.env
    volumes:
      - ./apps/backend:/app:rw
    depends_on:
      - database
  
  database:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
